### ISSUE TITLE
change employees?

### ISSUE THREAD

**Issue by alexandradm** [DocNow/docnow.github.io#16]
should we remove DC and DJS and add RA?

**Comment by edsu** [comment]
DC is technically still under contract, and when last I spoke with him he is ok with still being listed on the website.

If RA is Raff I think we can add him. Although I'm pretty sure we only have his time for the remainder of the summer. What to do with DJS is Vernon's call I think?

**Comment by edsu** [comment]
DC asked to be removed, so he was removed.
