### ISSUE TITLE
Header Links Not Working

### ISSUE THREAD

**Issue by edsu** [DocNow/docnow.github.io#4]
The following links in the header don't appear to be working:
- The Team
- Advisory Board

**Comment by edsu** [comment]
@alexandradm I'm not sure if it helps, but one thing I noticed when trying to figure out what was going on here is that if you remove the loading of `css/style.css` then the links work properly.

Obviously it doesn't look right with that css disabled, but I thought that might help you narrow down the problem.

**Comment by alexandradm** [comment]
@edsu hmm, ok, thanks. I will investigate further this week!

**Comment by edsu** [comment]
this was fixed in #6
